apiVersion: v1
kind: Pod
metadata:
  name: nginx-users-allowed
  labels:
    app: nginx-users
spec:
  securityContext:
    supplementalGroups:
      - 1990
    fsGroup: 1990
  containers:
    - name: nginx
      image: nginx
      securityContext:
        runAsUser: 1990
        runAsGroup: 1990
