apiVersion: v1
kind: Pod
metadata:
  name: nginx-users-disallowed
  labels:
    app: nginx-users
spec:
  securityContext:
    supplementalGroups:
      - 2500
    fsGroup: 2500
  containers:
    - name: nginx
      image: nginx
      securityContext:
        runAsUser: 2500
        runAsGroup: 2500
