apiVersion: v1
kind: Pod
metadata:
  name: nginx-test
  labels:
    app: nginx-test
spec:
  hostPID: false
  hostIPC: false
  securityContext:
    supplementalGroups:
      - 199
    fsGroup: 199  
  containers:
  - name: nginx
    image: nginx:latest
    command: ["/bin/sleep", "3600"]
    resources:
      limits:
        cpu: "100m"
        memory: "1Gi"
    ports:
    - containerPort: 900
      hostPort: 8080            
    volumeMounts:
      - mountPath: /cache
        name: cache-volume
        readOnly: true
    securityContext:
      runAsUser: 199
      runAsGroup: 199    
      allowPrivilegeEscalation: false          
      privileged: false        
  volumes:
    - name: cache-volume
      emptyDir: {}
