apiVersion: v1
kind: Pod
metadata:
  name: p1
  namespace: n3
  labels:
spec:
  containers:
  - name: p1
    image: nginx
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
      requests:
        cpu: 100m
        memory: 64Mi
    securityContext:
      allowPrivilegeEscalation: false
