apiVersion: v1
kind: Pod
metadata:
  name: nginx-host-filesystem
spec:
  hostPID: false
  hostIPC: false
  containers:
    - name: nginx
      image: nginx
      resources:
        limits:
          cpu: "100m"
          memory: "1Gi"
      volumeMounts:
        - mountPath: /cache
          name: cache-volume
          readOnly: true
  volumes:
    - name: cache-volume
      hostPath:
        path: /foo/bar
