apiVersion: v1
kind: Pod
metadata:
  name: nginx-users-disallowed
  labels:
    app: nginx-users
spec:
  securityContext:
    supplementalGroups:
      - 65536
    fsGroup: 65536
  containers:
    - name: nginx
      image: nginx
      securityContext:
        runAsUser: 65536
        runAsGroup: 65536
