apiVersion: v1
kind: Pod
metadata:
  name: p3
  namespace: n1
  labels:
    app: p3
spec:
  securityContext:
    supplementalGroups:
      - 199
    fsGroup: 199
  containers:
    - name: p3
      image: nginx
      securityContext:
        runAsNonRoot: true
        runAsUser: 199
#        runAsGroup: 199
